### PR TITLE
Ryan

### PR DESCRIPTION
**Pull request by Bigless27**

### CODE REVIEW

**Comment by sgharms** [comment]
@cdimartino do you have any direction on this?  I'm disinclined to want to ship User auth as part of the skeleton (see: 0d6d885bd77278a528cac57e2268ea0ec46e00fa).

**Comment by cdimartino** [comment]
Sorry this was not meant for this Org...  I must have opened it accidentally and lost track of it.  This was a regular PR for the copperheads org.  My apologies again.

**Comment by sgharms** [comment]
No sweat.  But sometimes you guys have good ideas we like to acquire ;)

**Comment by cdimartino** [comment]
I agree. :) I misspoke either way. This was a student attempting to open a pull request to me today! Dino why I thought I had created it. I do have updates for that challenge anyways, but they were primarily the change to the bcrypt gem in the gem file (new naming) and update of the jquery version to current.

**Comment by cdimartino** [comment]
I'll open a pr for those issues separately in the near future btw ;). Also, iOS is a shitty interface for typing anything with tech jargon, slang, or acronyms. It helpfully fixes them all for you :(

**Pull request closed without merging**
